Repository Ghanshyam89/GitHack, pull requests merged in 2022-10, with the labels that each got.

#1 I have added my details in index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#2 Updated the Logo Link
  index.html
Labels: invalid, spam

#3 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#5 I have addedd my details as <Your Name>
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#6 Update index.html and added new div container
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#7 Updated Footer
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#9 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#13 I have added my details as Shaikh Farhan
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#14 I have added my details as Niranjan Kurhade
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#15 I have added my details as Ramlakhan Lodhi
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#16 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#26 Added <Kush Pandey>
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#52 I've added my details as Anupriya Kushwaha
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
